/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0qFVgPhGuVn
 */
import { Button } from "@/components/ui/button"

export function FirstScreen() {
  return (
    <div className="bg-gradient-to-r from-gray-200 to-gray-300 min-h-screen p-8 text-gray-800 dark:text-gray-100">
      <main className="mt-20 text-center">
        <div className="mb-6 inline-block bg-white py-1 px-3 rounded-full text-sm font-semibold text-gray-800 dark:text-gray-100">
          <CloudLightningIcon className="inline mr-2 text-yellow-500" />
          Enhance your work with Lucy
        </div>
        <h1 className="text-6xl font-bold text-white leading-tight dark:text-gray-100">
          Let humans do,
          <br />
          what they really want to do{"\n              "}
        </h1>
        <p className="mt-6 text-lg text-white dark:text-gray-100">
          Lets do things out of adventure, curiosity, joy and passion.
          <br />
          We are not the robots anymore. We built one.
        </p>
        <div className="mt-10">
          <Button className="bg-white text-gray-800 dark:bg-gray-900 dark:text-white rounded-full">
            Bring to Life
          </Button>
          <Button className="ml-4 bg-transparent border border-white text-white rounded-full dark:border-gray-900">
            Create your Digital Clone
          </Button>
        </div>
      </main>
    </div>
  )
}


function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function CloudLightningIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 16.326A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 .5 8.973" />
      <path d="m13 12-3 5h4l-3 5" />
    </svg>
  )
}
